positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*.log
- job_name: xampp
  static_configs:
  - targets:
      - localhost
    labels:
      job: xampp
      agent: promtail
      application: xampp
      type: access
      __path__: "C:/xampp/apache/logs/access.log"
