apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: go-deployment
spec:
  selector:
    matchLabels:
      app: go-server
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: go-server
    spec:
      containers:
      - name: go-server
        image: acehanks/k8:v1
        ports:
        - containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: go-service
spec:
  selector:
    app: go-server
  type: LoadBalancer 
  ports: 
    - port: 5050
      protocol: TCP       
      targetPort: 9001
  