apiVersion: v1
kind: Service
metadata:
  name: go-service
spec:
  selector:
    app: go-server
  type: NodePort 
  ports:
    - nodePort: 30643  
      port: 5050        
      protocol: TCP
      targetPort: 9001  